language: shell
os: linux
dist: xenial


jobs:
  include:
    - name: Crawler
      language: python
      python: 3.8
      before_script: cd crawler/
      script: python helloworld.py
    - name: Server
      language: java
      jdk: openjdk11
      cache:
        directories:
          - $HOME/.m2
          - server/target/
      before_cache: rm -rf server/target/
      before_script: cd server/
      script:
        - mvn clean
        - mvn test
        - mvn verify
    - name: App-Compose
      env:
        - DOCKER_COMPOSE_VERSION=1.25.0
      services: docker
      before_script:
        - cd docker/compose
      script:
        - ./travis.sh
