language: shell
os: linux
dist: xenial


jobs:
  allow_failures:
    - name: "crawler.lint"

  include:
    - name: crawler.doc
      language: python
      python: 3.8
      install:
        - pip install -r crawler/requirements/doc.txt
      before_script:
        - cd crawler/doc/autodoc
      script:
        - make html SPHINXOPTS="-W --keep-going"
    - name: crawler.lint
      language: python
      python: 3.8
      install:
        - pip install -r crawler/requirements/dev.txt
      before_script:
        - cd crawler/
      script:
        - pylint *.py crawler/
    - name: crawler.test
      language: python
      python: 3.8
      install:
        - pip install -r crawler/requirements/dev.txt
      before_script:
        - cd crawler/
      script:
        - python -m tests
    - name: Server
      language: java
      jdk: openjdk11
      cache:
        directories:
          - $HOME/.m2
          - server/target/
      before_cache: rm -rf server/target/
      before_script: cd server/
      script:
        - mvn clean
        - mvn test
        - mvn verify
    - name: app.testing
      env:
        - DOCKER_COMPOSE_VERSION=1.25.0
      services: docker
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      before_script:
        - cd docker/compose
      script:
        - bash travis.sh
    - name: app.deployment
      if: branch = ci-cd
      services: docker
      before_install:
        - docker build -f docker/deployment/Dockerfile -t amosproject2/metadatahub .
      script:
        - docker run amosproject2/metadatahub 1 10
      after_success:
        - ./docker/deployment/deploy.sh
